---
- hosts: server
  gather_facts: false
  become: yes
  become_user: ubuntu
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:
    # Create Kubernetes replica set
    - name: Create deployment object
      k8s:
        state: present
        namespace: default
        src: deployment_ex.yaml
      

